const { createCustomerRecord, normalizeNote } = require("../../crm-sdk/src/customerRecord");
class PostgresCrmRepository {
 constructor({db}){this.db=db;}
 async getCustomer(tenantId,customerId){const r=await this.db.query(`SELECT payload FROM customers WHERE tenant_id=$1 AND customer_id=$2`,[tenantId,customerId]);return clone(r.rows[0]?.payload||null);}
 async upsertCustomer(input){const current=await this.getCustomer(input.tenantId,input.customerId);const record=createCustomerRecord({...(current||{}),...input,tags:input.tags??current?.tags,notes:input.notes??current?.notes,customFields:{...(current?.customFields||{}),...(input.customFields||{})},createdAt:current?.createdAt||input.createdAt});await this.db.query(`INSERT INTO customers(tenant_id,customer_id,name,phone,email,payload,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,COALESCE($7::timestamptz,now()),COALESCE($8::timestamptz,now())) ON CONFLICT(tenant_id,customer_id) DO UPDATE SET name=EXCLUDED.name,phone=EXCLUDED.phone,email=EXCLUDED.email,payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at`,[record.tenantId,record.customerId,record.name||null,record.phone||null,record.email||null,JSON.stringify(record),record.createdAt||null,record.updatedAt||null]);return clone(record);}
 async deleteCustomer(tenantId,customerId){await this.db.transaction(async c=>{await c.query(`DELETE FROM crm_activities WHERE tenant_id=$1 AND customer_id=$2`,[tenantId,customerId]);await c.query(`DELETE FROM customers WHERE tenant_id=$1 AND customer_id=$2`,[tenantId,customerId]);});return true;}
 async addNote(tenantId,customerId,note){const c=await this.getCustomer(tenantId,customerId);if(!c)return null;c.notes.push(normalizeNote(note));return this.upsertCustomer(c);}
 async addTag(tenantId,customerId,tag){const c=await this.getCustomer(tenantId,customerId);if(!c)return null;c.tags=[...new Set([...c.tags,String(tag).trim().toLowerCase()].filter(Boolean))];return this.upsertCustomer(c);}
 async removeTag(tenantId,customerId,tag){const c=await this.getCustomer(tenantId,customerId);if(!c)return null;c.tags=c.tags.filter(x=>x!==String(tag).trim().toLowerCase());return this.upsertCustomer(c);}
 async recordActivity(input){const activity={id:input.id||`act_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,type:input.type,data:input.data||{},capabilityId:input.capabilityId||'system',createdAt:input.createdAt||new Date().toISOString()};await this.db.query(`INSERT INTO crm_activities(id,tenant_id,customer_id,type,capability_id,payload,created_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::timestamptz)`,[activity.id,input.tenantId,input.customerId,activity.type,activity.capabilityId,JSON.stringify(activity),activity.createdAt]);return clone(activity);}
 async listActivities(tenantId,customerId,{limit=50}={}){const r=await this.db.query(`SELECT payload FROM crm_activities WHERE tenant_id=$1 AND customer_id=$2 ORDER BY created_at DESC LIMIT $3`,[tenantId,customerId,limit]);return r.rows.map(x=>clone(x.payload));}
 async searchCustomers(tenantId,query=''){const q=`%${String(query).toLowerCase()}%`;const r=await this.db.query(`SELECT payload FROM customers WHERE tenant_id=$1 AND ($2='%%' OR lower(COALESCE(name,'')) LIKE $2 OR lower(COALESCE(phone,'')) LIKE $2 OR lower(COALESCE(email,'')) LIKE $2) ORDER BY updated_at DESC LIMIT 100`,[tenantId,q]);return r.rows.map(x=>clone(x.payload));}
}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
module.exports={PostgresCrmRepository};
