class PostgresCommerceRepository {
  constructor({ db }) { this.db = db; }
  async getCart(tenantId, customerId) { const r=await this.db.query(`SELECT payload FROM carts WHERE tenant_id=$1 AND customer_id=$2 AND status='active' LIMIT 1`,[tenantId,customerId]); return clone(r.rows[0]?.payload||null); }
  async saveCart(cart) { await this.db.query(`INSERT INTO carts(id,tenant_id,customer_id,status,payload,created_at,updated_at) VALUES($1,$2,$3,$4,$5::jsonb,COALESCE($6::timestamptz,now()),COALESCE($7::timestamptz,now())) ON CONFLICT(tenant_id,customer_id) DO UPDATE SET id=EXCLUDED.id,status=EXCLUDED.status,payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at`,[cart.id,cart.tenantId,cart.customerId,cart.status||'active',JSON.stringify(cart),cart.createdAt||null,cart.updatedAt||null]); return clone(cart); }
  async clearCart(tenantId, customerId) { await this.db.query(`DELETE FROM carts WHERE tenant_id=$1 AND customer_id=$2`,[tenantId,customerId]); }
  async findOrderByIdempotencyKey(tenantId,key){if(!key)return null;const r=await this.db.query(`SELECT payload FROM orders WHERE tenant_id=$1 AND idempotency_key=$2 LIMIT 1`,[tenantId,key]);return clone(r.rows[0]?.payload||null);}
  async createOrder(order) { if(order.idempotencyKey){const existing=await this.findOrderByIdempotencyKey(order.tenantId,order.idempotencyKey);if(existing)return existing;} await this.db.query(`INSERT INTO orders(id,tenant_id,customer_id,status,total,currency,payload,created_at,updated_at,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,COALESCE($8::timestamptz,now()),COALESCE($9::timestamptz,now()),$10) ON CONFLICT(tenant_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING`,[order.id,order.tenantId,order.customerId,order.status,order.total,order.currency,JSON.stringify(order),order.createdAt||null,order.updatedAt||null,order.idempotencyKey||null]); return (order.idempotencyKey&&await this.findOrderByIdempotencyKey(order.tenantId,order.idempotencyKey))||clone(order); }
  async saveOrder(order) { const r=await this.db.query(`UPDATE orders SET status=$3,total=$4,currency=$5,payload=$6::jsonb,updated_at=COALESCE($7::timestamptz,now()) WHERE tenant_id=$1 AND id=$2 RETURNING payload`,[order.tenantId,order.id,order.status,order.total,order.currency,JSON.stringify(order),order.updatedAt||null]);if(!r.rows[0])throw new Error('Order not found');return clone(r.rows[0].payload); }
  async getOrder(tenantId, orderId) { const r=await this.db.query(`SELECT payload FROM orders WHERE tenant_id=$1 AND id=$2`,[tenantId,orderId]); return clone(r.rows[0]?.payload||null); }
  async listOrders(tenantId, customerId) { const r=await this.db.query(`SELECT payload FROM orders WHERE tenant_id=$1 AND customer_id=$2 ORDER BY created_at DESC`,[tenantId,customerId]); return r.rows.map(x=>clone(x.payload)); }
}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
module.exports={PostgresCommerceRepository};
