const test=require('node:test');const assert=require('node:assert/strict');const {buildContainer}=require('../apps/api/src/container');
let c;test.before(async()=>{c=await buildContainer()});test.after(async()=>{await c.registry.shutdownAll()});
const msg=(customerId,text,tenantId='default')=>c.executionEngine.process({tenantId,channel:'test',customerId,text});
test('universal semantic layer is domain-neutral and visible',async()=>{const r=await msg('sem-1','hello how are you doing today');assert.equal(r.intelligence.semantic.primaryAct,'small_talk');assert.equal(r.intelligence.domain.domainId,'retail');assert.match(r.reply,/doing well|well|thank/i)});
test('retail and cleaning resolve different schemas over same core',async()=>{const a=await msg('sem-2','hello','default');const b=await msg('sem-3','hello','cleaning-demo');assert.equal(a.intelligence.domain.domainId,'retail');assert.equal(b.intelligence.domain.domainId,'cleaning')});
test('shirt family excludes jeans',async()=>{const r=await msg('sem-4','can i get shirts');assert.equal(r.intelligence.selected.intent,'catalog.family_browse');assert.match(r.reply,/Cotton T-Shirt/);assert.match(r.reply,/Polo Shirt/);assert.doesNotMatch(r.reply,/Denim Jeans/)});
test('unsupported item preserves completed catalog state and goal',async()=>{const id='sem-5';await msg(id,'i want polo shirt');await msg(id,'white');await msg(id,'s');await msg(id,'3');const u=await msg(id,'i want some milk also');assert.match(u.reply,/milk/i);assert.equal(u.state.capabilityState.catalog.selectedAttributes.quantity,3);const r=await msg(id,'confirm my order');assert.equal(r.capabilityId,'commerce');assert.match(r.reply,/6,600/)});
test('cancel can be undone',async()=>{const id='sem-6';await msg(id,'i want polo shirt');await msg(id,'white');await msg(id,'s');await msg(id,'1');const x=await msg(id,'cancel my order');assert.equal(x.capabilityId,'system');const u=await msg(id,'undo cancel');assert.match(u.reply,/restore/i);assert.equal(u.state.capabilityState.catalog.selectedAttributes.quantity,1)});
test('roman urdu product list variants route to catalog',async()=>{const r=await msg('sem-7','konsy chezyn ap k pss hain');assert.equal(r.capabilityId,'catalog');assert.match(r.reply,/Available products|products/i)});
