const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
process.env.LOG_LEVEL='error';
const {buildContainer}=require('../apps/api/src/container');
async function chat(c,tenantId,customerId,text,channel='http'){return c.executionEngine.process({tenantId,customerId,channel,text});}

test('generic footwear language routes to category without inventing quantity',async()=>{const c=await buildContainer();const r=await chat(c,'default','ci-shoes','Can I get shoes?');assert.equal(r.capabilityId,'catalog');assert.equal(r.intelligence.selected.intent,'catalog.category_browse');assert.equal(r.intelligence.entities.categoryId,'footwear');assert.match(r.reply,/Running Shoes/);assert.match(r.reply,/Comfort Slides/);assert.equal(r.state.capabilityState.catalog.selectedAttributes?.quantity,undefined);await c.registry.shutdownAll();});

test('English do is never interpreted as Roman Urdu quantity two',async()=>{const c=await buildContainer();const r=await chat(c,'default','ci-do','do you have backpacks');assert.equal(r.capabilityId,'catalog');assert.equal(r.intelligence.entities.quantity,null);assert.doesNotMatch(r.reply,/Quantity:\s*2/);await c.registry.shutdownAll();});

test('checkout comment is an interruption and is not saved as customer name',async()=>{const c=await buildContainer();const id='ci-comment';await chat(c,'default',id,'i want silver sunglasses');await chat(c,'default',id,'1');await chat(c,'default',id,'confirm order');const r=await chat(c,'default',id,'wah g kia bat hai itny mehngy shoes');assert.equal(r.capabilityId,'commerce');assert.equal(r.intelligence.interruption.type,'price_comment');assert.equal(r.state.capabilityState.commerce.pendingField,'name');const cart=await c.commerceRepository.getCart('default',id);assert.equal(cart.checkout.name,null);assert.match(r.reply,/Rs1,800/);await c.registry.shutdownAll();});

test('name correction and global cancellation work from checkout',async()=>{const c=await buildContainer();const id='ci-correction';await chat(c,'default',id,'i want black wireless earbuds');await chat(c,'default',id,'1');await chat(c,'default',id,'confirm order');await chat(c,'default',id,'Zeeshan Ahmad');let r=await chat(c,'default',id,'this is not my name');assert.equal(r.capabilityId,'commerce');assert.equal(r.state.capabilityState.commerce.pendingField,'name');r=await chat(c,'default',id,'cancel my order');assert.equal(r.capabilityId,'system');assert.equal(r.state.capabilityState.commerce.mode,undefined);assert.match(r.reply,/cancel/i);await c.registry.shutdownAll();});

test('cleaning conversation adapter extracts date and duration vocabulary',async()=>{const c=await buildContainer();const tenant=c.tenantRepository.getById('cleaning-demo');const state=require('../packages/state/src/stateSchema').createInitialState({tenantId:'cleaning-demo',conversationId:'x',channel:'http',customerId:'u',language:'english'});const a=await c.conversationIntelligenceEngine.analyze({tenant,message:{tenantId:'cleaning-demo',channel:'http',customerId:'u',text:'i want a cleaner tomorrow for two hours'},state,services:c.executionEngine.services});assert.equal(a.selected.capabilityId,'cleaning');assert.equal(a.entities.date,'tomorrow');assert.equal(a.entities.durationHours,2);await c.registry.shutdownAll();});

test('replay records intelligence, state before and state after',async()=>{const c=await buildContainer();const r=await chat(c,'default','ci-replay','show me shoes');assert.ok(r.replayId);const replay=await c.replayService.get(r.replayId);assert.equal(replay.message.text,'show me shoes');assert.ok(replay.intelligence);assert.ok(replay.stateBefore);assert.ok(replay.stateAfter);await c.registry.shutdownAll();});

test('conversation compliance corpus passes all shipped cases',async()=>{const c=await buildContainer();const files=['retail/core.json','cleaning/core.json','shared/global.json'];let cases=0;for(const file of files){const dataset=JSON.parse(fs.readFileSync(path.join(__dirname,'datasets',file),'utf8'));for(let i=0;i<dataset.cases.length;i++){const tc=dataset.cases[i];const id=`compliance-${file.replace(/\W/g,'')}-${i}`;for(const turn of tc.turns){const r=await chat(c,dataset.tenantId,id,turn.text,'compliance');const e=turn.expect||{};const intent=r.intelligence?.selected?.intent||null;if(e.capabilityId)assert.equal(r.capabilityId,e.capabilityId,`${file}/${tc.name}: ${turn.text}`);if(e.intent)assert.equal(intent,e.intent,`${file}/${tc.name}: ${turn.text}`);if(e.replyContains)assert.ok(String(r.reply).toLowerCase().includes(String(e.replyContains).toLowerCase()),`${file}/${tc.name}: reply missing ${e.replyContains}`);for(const[k,v]of Object.entries(e.entities||{}))assert.deepEqual(r.intelligence?.entities?.[k],v,`${file}/${tc.name}: entity ${k}`);}cases++;}}assert.ok(cases>=120);await c.registry.shutdownAll();});
