const { ProductEmbeddingMatcher, WORD_WEIGHT, BIGRAM_WEIGHT, CHAR_WEIGHT, EXACT_ALIAS_THRESHOLD, STRONG_MATCH_THRESHOLD, PARTIAL_MATCH_THRESHOLD, MIN_THRESHOLD } = require('./productEmbeddingMatcher');

module.exports = {
  ProductEmbeddingMatcher,
  WORD_WEIGHT,
  BIGRAM_WEIGHT,
  CHAR_WEIGHT,
  EXACT_ALIAS_THRESHOLD,
  STRONG_MATCH_THRESHOLD,
  PARTIAL_MATCH_THRESHOLD,
  MIN_THRESHOLD,
};
