BEGIN;
CREATE TABLE IF NOT EXISTS nova_schema_migrations(version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tenants(id text PRIMARY KEY,name text NOT NULL,domain text,profile jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customers(tenant_id text NOT NULL,customer_id text NOT NULL,name text,phone text,email text,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,customer_id));
CREATE INDEX IF NOT EXISTS customers_tenant_phone_idx ON customers(tenant_id,phone);
CREATE TABLE IF NOT EXISTS crm_activities(id text PRIMARY KEY,tenant_id text NOT NULL,customer_id text NOT NULL,type text NOT NULL,capability_id text,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS crm_activities_customer_idx ON crm_activities(tenant_id,customer_id,created_at DESC);
CREATE TABLE IF NOT EXISTS carts(id text NOT NULL,tenant_id text NOT NULL,customer_id text NOT NULL,status text NOT NULL DEFAULT 'active',payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,customer_id));
CREATE TABLE IF NOT EXISTS orders(id text PRIMARY KEY,tenant_id text NOT NULL,customer_id text NOT NULL,status text NOT NULL,total numeric(14,2),currency text,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders(tenant_id,customer_id,created_at DESC);
CREATE TABLE IF NOT EXISTS bookings(id text PRIMARY KEY,tenant_id text NOT NULL,customer_id text NOT NULL,conversation_id text,status text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS bookings_customer_idx ON bookings(tenant_id,customer_id,created_at DESC);
CREATE TABLE IF NOT EXISTS service_requests(id text PRIMARY KEY,tenant_id text NOT NULL,customer_id text NOT NULL,kind text NOT NULL,status text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS service_requests_customer_idx ON service_requests(tenant_id,customer_id,kind,created_at DESC);
CREATE TABLE IF NOT EXISTS knowledge_sources(id text PRIMARY KEY,tenant_id text NOT NULL,title text,type text,evidence_type text,priority integer,status text NOT NULL DEFAULT 'active',metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversation_records(id bigserial PRIMARY KEY,tenant_id text NOT NULL,conversation_id text NOT NULL,customer_id text,channel text,role text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS conversation_records_lookup_idx ON conversation_records(tenant_id,conversation_id,created_at DESC);
INSERT INTO nova_schema_migrations(version) VALUES('001_v7_core') ON CONFLICT DO NOTHING;
COMMIT;
